### ISSUE TITLE
wasm-pack build not producing results as advertised/expected

### ISSUE THREAD

**Issue by avlo** [brunoamancio/IOTA-SmartContracts-Template-Base#1]
hello.  thanks for your template.  i'm attempting to validate proper usage and functionality via following steps using existing wasp donatewithfeedback.rs SC:

1. copy existing `iotaledger/wasp/contracts/rust/donatewithfeedback/src/donatewithfeedback.rs` SC to `IOTA-SmartContracts/smartcontract/rust/src/donatewithfeedback.rs`
2. `cd iotaledger/wasp/contracts/rust/donatewithfeedback/src/`
3. run `wasm-pack build` command
4. expecting to find newly created `IOTA-SmartContracts/smartcontract/rust/pkg/donatewithfeedback_bg.wasm` in `pkg` directory **_however, it is not there, nor anywhere else in the template directory structure_**

can you please advise if i'm missing something or performing a step incorrectly?

**Comment by brunoamancio** [comment]
I suggest running the default SC which you find directly on the template first.

With that said, try deleting the file `rust/src/lib.rs`, then rename the file `rust/src/donatewithfeedback.rs` to `rust/src/lib.rs` and run wasm-pack build from the rust directory and try again. Keep in mind that you need to change the name of the function you're calling in the unit test, so it matches your contracts.

**Comment by avlo** [comment]
test modifications working.  much thanks for your time and expertise, very helpful!
